$(function(){
    console.log($(document))
    console.log($(document).context.title)
    console.log($("li"))
    console.log($("li").length)
    console.log($("li").eq(5).html())
    console.log($("li:eq(5)"))
    console.log($("li:eq(5)").html())
    console.log($("#div1").html())
    console.log($("#div1").text())
    console.log($(".box"))
    console.log($("li:first").text())
    console.log($("li:last").text())
    console.log($("li:even"))
    console.log($("li:odd"))
    console.log($(":header"))
    console.log($(":focus"))
    console.log($("[class]"))
    console.log($("ul[class]"))
    console.log($("[name=milkman]"))
    console.log($("input[name^=m]"))
    console.log($("input[name$=2]"))
    console.log($("input[name*=man]"))
    console.log($("form input").length)
    console.log($("form").find("input").length)
    console.log($("form > input").length)
    console.log($("form").children("input").length)
    console.log($("form").children("input").length)
    console.log($("form + input"))
    console.log($("form ~ input"))
})
